### ISSUE TITLE
Describe what the module does

### ISSUE THREAD

**Issue by freaktechnik** [BtbN/ZncTwitchTMI#1]
This module looks interesting - especially since twitch's IRC does some weird things. I've tried to find out what exactly the mulde does, but so far all I've found is, that it requests the membership capability, sets the topic and does something with FrankerZ.

It'd be nice if you could describe its features more in the readme or similar.

**Comment by BtbN** [comment]
You summed it up quite accurately.
It's basicaly my personal "Make Twitch IRC more useable" module.
- It sets the channel topic by periodicaly downloading the stream description.
- It used to silence the jtv bot, which seems to be gone almost completely now.
- Requests the membership capability. Without that, you no longer have a userlist.
- Responds to FrankerZ with FrankerZ, because why not.

Planned features: Propper capitalization of nicknames. My tag-parsing PR has to be merged into ZNC for that to be possible.

**Comment by freaktechnik** [comment]
The jtv bot still gives the output for twitch specific commands issued via the . aliases (.mods, .host, .color, .help etc.). I am currently using the perform module to get the capability, so I don't see the need for this module (yet).
